version: '3.3'

services:
  db:
    build:
      dockerfile: deployments/docker/database/Dockerfile
      context: .
    expose:
      - "${DATABASE_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  server:
    build:
      dockerfile: deployments/docker/api/Dockerfile
      context: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: "${SERVER_PORT}"
      SERVER_HOST: "${SERVER_HOST}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    depends_on:
      - db
